version: '3'

services:

  rc_bot:
    container_name: rc_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb:27017"
    command: bash -c "python bot.py"
    restart: unless-stopped

  rc_dash:
    container_name: rc_dash
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - 8501:8501
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb:27017"
    command: bash -c "streamlit run RC_Overview.py"
    restart: unless-stopped



networks:
  default:
    name: v4vapi_default
