version: '3'

services:

  rc_bot:
    container_name: rc_bot
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    env_file:
      - ".env"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb:27017"
    command: bash -c "python bot.py"
    restart: unless-stopped
    networks:
      - hive-network


  rc_dash:
    container_name: rc_dash
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    env_file:
      - ".env"
    ports:
      - "${LOCAL_TAILSCALE_IP}:8501:8501"
      - "127.0.0.1:8501:8501"
      - "127.0.1.1:8501:8501"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb:27017"
    command: bash -c "streamlit run Podping.py"
    restart: unless-stopped
    networks:
      - hive-network

  pricefeed:
    container_name: v4vapp-pricefeed
    image: brianoflondon/v4vapphivepricefeed:latest
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    env_file:
      - ".env"
    restart: unless-stopped

networks:
  hive-network:
    external: true
