version: '3'

services:

  rc_bot:
    container_name: rc_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb:27017"
    command: bash -c "python bot.py"
    restart: unless-stopped
    networks:
      - pingslurp_pingslurp
      - hive-network


  rc_dash:
    container_name: rc_dash
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - "${LOCAL_TAILSCALE_IP}:8501:8501"
      - "127.0.0.1:8501:8501"
      - "127.0.1.1:8501:8501"
    # environment:
    #   DB_CONNECTION: "mongodb://mongodb:27017"
    command: bash -c "streamlit run Podping.py"
    restart: unless-stopped
    networks:
      - pingslurp_pingslurp
      - hive-network


networks:
  pingslurp_pingslurp:
    external: true
  hive-network:
    external: true