version: '3'

services:

  v4vapi:
    container_name: rc_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    command: bash -c "python bot.py"
    # restart: unless-stopped
